version: '3.8'
services:
  api:
    container_name: nest_api
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: .
        target: /src
    networks:
      - backend

  mysql:
    container_name: nest_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    hostname: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - ./docker/mysql/init/:/docker-entrypoint-initdb.d
    # security_opt:
    #   - seccomp:uncofined
    networks:
      - backend

  phpmyadmin:
    container_name: nest_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=docker
      - PMA_PASSWORD=docker
    ports:
      - 8080:80

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
